### ISSUE TITLE
Update the Game's Standard Resolution (and Scenes) to 1920x1080

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/SpaceResortMurder#126]

**Comment by timeracers** [comment]
Simply stretching everything to 1.2 times the size to make the game's standard resolution 1920x1080 isn't going to accomplish anything that setting the Display to be 1920x1080 with 1.2 scale won't.

**Comment by SilasReinagel** [comment]
The challenge is Sprintfonts, Icons, and Pixel Button sizes. We'll want to ensure that even though the Backgrounds overlays change size that the fonts look correct with each of the elements and there shouldn't be pixel tearing on the buttons/icons.

Those are the ones whose number might need to change or who might need to be exempt from scaling.
