### ISSUE TITLE
Track location for various menu type screens to be able to navigate back to the location you were at

### ISSUE THREAD

**Issue by ZavixDragon** [EnigmaDragons/SpaceResortMurder#56]

**Comment by timeracers** [comment]
You can create the scene with passing args, then navigate to it.

**Comment by SilasReinagel** [comment]
I don't see any checkin associated with this ticket. Moving it back into the queue.

As per the description "Navigate" back must work without an instance of a scene and without calling any constructors. 

`Scene.NavigateBack()` or something.

**Comment by ZavixDragon** [comment]
We discussed this yesterday and we actually don't need this feature at all since we never would want to navigate back to the scene before we only would want to navigate to the location we are at. which can be stored in game state.
